package com.devflow.backend.entity;

public enum ActivityType {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_COMPLETED,
    PROJECT_ARCHIVED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_COMPLETED,
    TASK_ASSIGNED,
    TASK_COMMENTED,
    FILE_UPLOADED,
    MILESTONE_REACHED,
    DEADLINE_CHANGED
}